print("HIT HERE")
vim.keymap.set("n", "<leader>db", "<cmd> DapToggleBreakpoint <CR>", { desc = "[D]ebug [B]reakpoint toggle"})
vim.keymap.set("n", "<leader>dpr", function()
    require('dap-python').test_method()
end, { desc = "[D]ebug [P]ython run"})
